// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC640TQUL2Qk88dZks5L252I2pJGArqseg',
    appId: '1:328322134096:web:3f839c34908d33df8ea155',
    messagingSenderId: '328322134096',
    projectId: 'iti-course-a4b5f',
    authDomain: 'iti-course-a4b5f.firebaseapp.com',
    storageBucket: 'iti-course-a4b5f.appspot.com',
    measurementId: 'G-C31XCG9998',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIbA1plW8dGM3dfamZI1X8HX1MOkSIT2A',
    appId: '1:328322134096:android:97450ed331ef0aac8ea155',
    messagingSenderId: '328322134096',
    projectId: 'iti-course-a4b5f',
    storageBucket: 'iti-course-a4b5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl7t8vPLAQdbL5s3SXwNlk5v4JcSRh_JQ',
    appId: '1:328322134096:ios:eef783e110f21eb68ea155',
    messagingSenderId: '328322134096',
    projectId: 'iti-course-a4b5f',
    storageBucket: 'iti-course-a4b5f.appspot.com',
    iosClientId: '328322134096-9rqnd8v1mfu450u7oo7bbhir92034pqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl7t8vPLAQdbL5s3SXwNlk5v4JcSRh_JQ',
    appId: '1:328322134096:ios:439a6c1c42d7256c8ea155',
    messagingSenderId: '328322134096',
    projectId: 'iti-course-a4b5f',
    storageBucket: 'iti-course-a4b5f.appspot.com',
    iosClientId: '328322134096-ng7ghhv0rmd00e9ih1ud1ooo496cjr35.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
